### PR TITLE
Add Anchor components

### LINKED ISSUE #9: Anchor button ref to top. Anchor section to navigate through the website

### PR DESCRIPTION
**Pull request by R-Jim**
Here is a sample of it, the SVG will be replaced with the aqua one.
image

Here is the implementation
`<AnchorMultipleSection position={AnchorSectionPosition.RIGHT} anchors={anchors} activeHref={this.state.activeHref} />`
This will work for most **id assigned** component `<div id="your_ref_id"/>`

To use the current active anchor section add this to the code segment
```
<AnchorSupportedSection href="#your_ref_id" onVisible={wrapper_set_active_href_function()}>
     <div>your component here</div>
</AnchorSupportedSection>
```

### CODE REVIEW

**Comment by zapplecat** [comment]
I literally have smol frontend brain so I don't comprehend how the component works. Can you show me an example how this component is used?

**Comment by DuongTyler** [comment]
> I literally have smol frontend brain so I don't comprehend how the component works. Can you show me an example how this component is used?

I'm pretty sure this is for the separators that we have. The ones with the buttons that bring you down to some part of the site. Like this.
image

**Comment by zapplecat** [comment]
> > I literally have smol frontend brain so I don't comprehend how the component works. Can you show me an example how this component is used?
> 
> I'm pretty sure this is for the separators that we have. The ones with the buttons that bring you down to some part of the site. Like this.
> image

I'd like to see like a snippit of sample code for the multi section anchor. (I'd admit, I forgot how components worked until I looked in one, and I'm pretty sure I know how it works now).

I'll come back and re-review in a little.

**Comment by R-Jim** [comment]
Here is a sample of it, the SVG will be replaced with the aqua one.
image

Here is the implementation
`<AnchorMultipleSection position={AnchorSectionPosition.RIGHT} anchors={anchors} activeHref={this.state.activeHref} />`
This will work for most **id assigned** component `<div id="your_ref_id"/>`

To use the current active anchor section add this to the code segment
```
<AnchorSupportedSection href="#your_ref_id" onVisible={wrapper_set_active_href_function()}>
     <div>your component here</div>
</AnchorSupportedSection>
```

**Comment by DuongTyler** [comment]
> Here is a sample of it, the SVG will be replaced with the aqua one.
> image
> 
> Here is the implementation
> `<AnchorMultipleSection position={AnchorSectionPosition.RIGHT} anchors={anchors} activeHref={this.state.activeHref} />`
> This will work for most **id assigned** component `<div id="your_ref_id"/>`
> 
> To use the current active anchor section add this to the code segment
> 
> ```
> <AnchorSupportedSection href="#your_ref_id" onVisible={wrapper_set_active_href_function()}>
>      <div>your component here</div>
> </AnchorSupportedSection>
> ```

This looks really useful, but I don't know how we are going to style it to look good on the page. I think its probably OK to merge but you might want to make a really rough sketch on top of the current design we have so we can implement it to look nice. And also so the artists know what to work with.
This is the design mockup: https://cdn.discordapp.com/attachments/760308342941286411/847723413333737502/aqua_site_concept.png

**Review by DuongTyler — APPROVED** [review]
anyways, lgtm

**Pull request merged**
